import { State } from './types';

export const stateManifest: State[] = [
  { stateName: 'Alabama', stateAbbr: 'AL' },
  // { stateName: 'Alaska', stateAbbr: 'AK' },
  { stateName: 'Arizona', stateAbbr: 'AZ' },
  // { stateName: 'Arkansas', stateAbbr: 'AR' },
  // { stateName: 'California', stateAbbr: 'CA' },
  { stateName: 'Colorado', stateAbbr: 'CO' },
  // { stateName: 'Connecticut', stateAbbr: 'CT' },
  // { stateName: 'Delaware', stateAbbr: 'DE' },
  // { stateName: 'District of Columbia', stateAbbr: 'DC' },
  // { stateName: 'Florida', stateAbbr: 'FL' },
  { stateName: 'Georgia', stateAbbr: 'GA' },
  // { stateName: 'Hawaii', stateAbbr: 'HI' },
  // { stateName: 'Idaho', stateAbbr: 'ID' },
  // { stateName: 'Illinois', stateAbbr: 'IL' },
  { stateName: 'Indiana', stateAbbr: 'IN' },
  // { stateName: 'Iowa', stateAbbr: 'IA' },
  // { stateName: 'Kansas', stateAbbr: 'KS' },
  { stateName: 'Kentucky', stateAbbr: 'KY' },
  // { stateName: 'Louisiana', stateAbbr: 'LA' },
  // { stateName: 'Maine', stateAbbr: 'ME' },
  // { stateName: 'Montana', stateAbbr: 'MT' },
  // { stateName: 'Nebraska', stateAbbr: 'NE' },
  // { stateName: 'Nevada', stateAbbr: 'NV' },
  // { stateName: 'New Hampshire', stateAbbr: 'NH' },
  // { stateName: 'New Jersey', stateAbbr: 'NJ' },
  // { stateName: 'New Mexico', stateAbbr: 'NM' },
  // { stateName: 'New York', stateAbbr: 'NY' },
  // { stateName: 'North Carolina', stateAbbr: 'NC' },
  // { stateName: 'North Dakota', stateAbbr: 'ND' },
  // { stateName: 'Ohio', stateAbbr: 'OH' },
  // { stateName: 'Oklahoma', stateAbbr: 'OK' },
  // { stateName: 'Oregon', stateAbbr: 'OR' },
  // { stateName: 'Maryland', stateAbbr: 'MD' },
  // { stateName: 'Massachusetts', stateAbbr: 'MA' },
  // { stateName: 'Michigan', stateAbbr: 'MI' },
  // { stateName: 'Minnesota', stateAbbr: 'MN' },
  // { stateName: 'Mississippi', stateAbbr: 'MS' },
  // { stateName: 'Missouri', stateAbbr: 'MO' },
  // { stateName: 'Pennsylvania', stateAbbr: 'PA' },
  // { stateName: 'Rhode Island', stateAbbr: 'RI' },
  // { stateName: 'South Carolina', stateAbbr: 'SC' },
  // { stateName: 'South Dakota', stateAbbr: 'SD' },
  { stateName: 'Tennessee', stateAbbr: 'TN' },
  { stateName: 'Texas', stateAbbr: 'TX' },
  // { stateName: 'Utah', stateAbbr: 'UT' },
  // { stateName: 'Vermont', stateAbbr: 'VT' },
  // { stateName: 'Virginia', stateAbbr: 'VA' },
  // { stateName: 'Washington', stateAbbr: 'WA' },
  // { stateName: 'West Virginia', stateAbbr: 'WV' },
  // { stateName: 'Wisconsin', stateAbbr: 'WI' },
  // { stateName: 'Wyoming', stateAbbr: 'WY' },
];
